### PR TITLE
add webrtc to multiaddr

### PR DESCRIPTION
**Pull request by melekes**
Refs https://github.com/libp2p/specs/pull/412

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
Why is this a different value than the one in https://github.com/multiformats/multiaddr/pull/131?

**Comment by melekes** [comment]
> Why is this a different value than the one in [multiformats/multiaddr#131](https://github.com/multiformats/multiaddr/pull/131)?

wasn't sure how code issuance works. changed to 280

**Review by marten-seemann — APPROVED** [review]

**Review by mxinden — APPROVED** [review]
Looks good to me. Thanks @melekes.

I am not a maintainer of this repository. @rvagg @Stebalien are you fine with us merging here?

**Comment by rvagg** [comment]
@mxinden @marten-seemann yeap, you have pretty much free-range on the `multiaddr` entries as far as I'm concerned, as long as you don't stray too low and get into the precious single-byte range <= `0x7f` and keep the validation script happy. Go ahead and merge both of these if they're good to go.

**Pull request merged**
