### PR TITLE
Assign a unique code to QUIC

### PR DESCRIPTION
**Pull request by Stebalien**
It conflicted with CBOR.

### CODE REVIEW

**Comment by Stebalien** [comment]
@lgierth?

**Comment by lgierth** [comment]
LGTM :+1: @marten-seemann what do you thing?

**Comment by marten-seemann** [comment]
How can there be a conflict, I thought I updated all multicodec repos when I added QUIC here?

I'm fine with merging this, QUIC has not yet been merged into IPFS, so there won't be any problems from that side.

**Comment by Stebalien** [comment]
Really bad luck. It looks like two PRs were merged one after another without any rebasing.

quic: https://github.com/multiformats/multicodec/blob/a21d79a394cb23169ea846ef27ad17bb8c0f63d2/table.csv
cbor: https://github.com/multiformats/multicodec/blob/c144a5ff48835ad79cc448d930b9ce4b5afbc7ee/table.csv

**Comment by Stebalien** [comment]
@lgierth I can't merge this. Could you?

**Comment by lgierth** [comment]
@Stebalien invited you

**Comment by Stebalien** [comment]
@lgierth Thanks!

**Pull request merged**
