### PR TITLE
Adding Skein hash to the mix

### PR DESCRIPTION
**Pull request by DonaldTsang**
Skein is created by Bruce Schneier, one of the leader in cryptography.
It is as fast as BLAKE, faster than all other SHA3 finalists and SHA2.

Skein hashes can have arbitrary lengths up to 1024 bits.
A longer hash means files are less likely to have hash collisions.
They can also produce shorter hashes for higher speed.

Using b3xx code for 256-XXX, 512-XXX and 1024-XXX skein hashes would be good.
There are only 224 hashes in total (assuming we exclude hashes not multiple of 8).

References:
http://www.skein-hash.info/sites/default/files/skein1.3.pdf
www.skein-hash.info/sites/default/files/NIST_CD_102610.zip

Python implementation: https://pythonhosted.org/pyskein
Java, C and Go: https://github.com/wernerd/Skein3Fish

https://github.com/multiformats/multihash/pull/83
https://github.com/multiformats/go-multihash/pull/52
https://github.com/multiformats/js-multihash/pull/34

### CODE REVIEW

**Comment by Kubuxu** [comment]
@diasdavid LGTY, LGTM.

**Comment by DonaldTsang** [comment]
@Kubuxu Thanks.

**Comment by Kubuxu** [comment]
@whyrusleeping @lgierth can you tick off on that please?

**Comment by DonaldTsang** [comment]
@daviddias I did my own research into what Hashes are useful.
Out of all the hashes in SHA3 second and third round, only a few matters
- [x] BLAKE and BLAKE2 (built to be fast)
- [x] SHA3, SHAKE, KangarooTwelve and M14 (built to be faster than BLAKE2)
- [x] Skein (at least faster than SHA2, has 1024-bit options)
- [ ] Blue Midnight Wish (round 2, near miss for finalist, faster than SHA1)
- [ ] ECHO (round2, faster than SHA1, uses AES instructions for speedup)
- [ ] SHAVite3  (round2, faster than SHA1, uses AES instructions for speedup)
- [ ] SHABAL (round2, faster than SHA256, uses AES instructions for speedup)
- [ ] Cubehash 8/32 (modified, faster than SHA1, slightly insecure, easy to write)

**Comment by DonaldTsang** [comment]
| quartile  | median | quartile | hash             | length | type      | 
|:---------:|:------:|:--------:|:----------------:|:------:|:---------:| 
| 2.20      | 2.21   | 2.23     | k12              | any    | Post-SHA3 | 
| 2.54      | 2.55   | 2.57     | md4              |  128   | legacy    | 
| 2.53      | 2.58   | 2.60     | bmw512           |  512   | <= This   | 
| 2.71      | 2.72   | 2.75     | echo256          |  256   | <= This   | 
| 2.91      | 2.92   | 2.93     | blake2b          |  512   | Post-SHA3 | 
| 2.95      | 2.98   | 3.00     | shavite3512      |  512   | <= This   | 
| 3.01      | 3.06   | 3.20     | echosp256        |  256   | <= This   | 
| 3.04      | 3.06   | 3.09     | sha1             |  160   | legacy    | 
| 3.34      | 3.35   | 3.37     | shavite3256      |  256   | <= This   | 
| 3.52      | 3.54   | 3.55     | cubehash832      |  512   | <= This   | 
| 3.98      | 4.02   | 4.05     | keccakc256treed2 |  256   | tree-SHA3 | 
| 3.35      | 4.05   | 4.92     | bmw256           |  256   | <= This   | 
| 4.04      | 4.26   | 4.70     | blake2s          |  256   | Post-SHA3 | 
| 4.31      | 4.33   | 4.35     | md5              |  128   | legacy    | 
| 4.39      | 4.45   | 4.49     | sha384           |  384   | legacy    | 
| 4.43      | 4.47   | 4.51     | shabal512        |  512   | <= This   | 
| 4.20      | 4.48   | 4.95     | sha512           |  512   | legacy    | 
| 4.45      | 4.48   | 4.52     | skein512512      |  512   | Skein     | 
| 4.41      | 4.48   | 4.63     | blake512         |  512   | BLAKE     | 
| 4.47      | 4.51   | 4.54     | skein512256      |  256   | Skein     | 
| 4.49      | 4.52   | 4.57     | shake128         | any    | SHA3+     | 
| 4.49      | 4.57   | 4.70     | echosp512        |  512   | <= This   | 
| 4.64      | 4.67   | 4.72     | blake64          |  512   | old-BLAKE | 
| 4.65      | 4.68   | 4.70     | shabal256        |  256   | <= This   | 
| 4.89      | 4.93   | 4.98     | keccakc512treed2 |  512   | tree-SHA3 | 
| 4.99      | 5.03   | 5.07     | bblake256        |  256   | TwinBLAKE | 
| 5.02      | 5.05   | 5.08     | bash256          |  256   | mystery   | 
| 5.33      | 5.35   | 5.38     | blake32          |  256   | old-BLAKE | 
| 5.65      | 5.68   | 5.71     | skein10241024    | 1024   | Skein     | 
| 5.55      | 5.78   | 6.53     | sha3224          |  224   | SHA3      | 
| 5.63      | 5.95   | 6.57     | blake256         |  256   | BLAKE     | 
| 5.91      | 6.06   | 6.12     | shake256         | any    | SHA3+     | 
| 5.88      | 6.08   | 6.12     | sha3256          |  256   | SHA3      | 
| 5.61      | 6.12   | 6.59     | keccakc256       |  256   | old-SHA3  | 
| 6.20      | 6.53   | 7.09     | bash384          |  384   | mystery   | 
| 6.61      | 6.65   | 6.69     | sha256           |  256   | legacy    | 
| 6.64      | 6.67   | 6.72     | sha224           |  224   | legacy    |

**Pull request merged**
