### PR TITLE
reformat table

### PR DESCRIPTION
**Pull request by Stebalien**
Sort the table by code and replace the sections with tags.

Inspired by https://github.com/multiformats/multicodec/pull/116 but rebased on master. This version also puts the description last as it's optional.

This PR _also_ includes an interactive table viewer (which we can improve over time).

### CODE REVIEW

**Comment by Stebalien** [comment]
@Zolmeister apologies for commandeering your PR. Does this look good to you?

**Comment by Stebalien** [comment]
Note: The "viewer" is currently viewing master.

**Comment by Zolmeister** [comment]
@Stebalien the sort order is different (numeric value vs alphabetical, e.g. `0x11` is not next to `0x1100`), but probably more correct given https://github.com/multiformats/multicodec/issues/115 so yes, looks good

**Comment by Stebalien** [comment]
Ah, yeah, I sorted numerically. Emacs FTW!

**Comment by Kubuxu** [comment]
@Stebalien what do you think about re-adding some tabs so csv is more readable by itself?

**Comment by Stebalien** [comment]
Done.

**Comment by vmx** [comment]
Thanks a lot @Stebalien. It's been on my TODO list, but you made it happen!

**Pull request merged**
