### PR TITLE
Add BLS 12-381 g1 and g2 public key concatenated identifier

### PR DESCRIPTION
**Pull request by tplooker**
For certain signatures such as https://github.com/mattrglobal/bbs-signatures it is useful to have a single private key have a corresponding public key in both the G1 and G2 fields.

### CODE REVIEW

**Comment by OR13** [comment]
Looking forward to using this representation.

**Comment by OR13** [comment]
@rvagg @vmx can we get a review of this? let us know if we need to make any adjustments... the reason we need an encoding for both keys concatenated is to support https://github.com/w3c-ccg/ldp-bbs2020/issues/37

**Comment by vmx** [comment]
@OR13 could you please put it after `ed25519-pub`, we currently sort by code value (so that it's easier to spot if some value is already taken).

**Comment by tplooker** [comment]
@vmx done

**Comment by vmx** [comment]
> we probably should have put `bls12_381*` in the two-byte range

It is in the 2-byte range. Everything > `0x80` is in the two-byte range.

**Review by vmx — APPROVED** [review]

**Pull request merged**
