### PR TITLE
Add Curve25519 private key.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
* we have the pubkey @ `0xec`
* we've previously agreed (and continued to have discussions about) private keys in the table
so this seems fine to me

**Comment by msporny** [comment]
> * we've previously agreed (and continued to have discussions about) private keys in the table
>   so this seems fine to me

Note that there already is a private key in the table -- ed25519-priv

**Comment by OR13** [comment]
Would be nice to register support for NIST curves as well.

**Comment by OR13** [comment]
Related PRs...

https://github.com/multiformats/multicodec/pull/194

https://github.com/multiformats/multicodec/pull/210

**Pull request merged**
