### PR TITLE
chore: add deprecations to p2p-webrtc-star, p2p-webrtc-direct, and p2…

### PR DESCRIPTION
**Pull request by p-shahi**
…p-stardust

### CODE REVIEW

**Comment by p-shahi** [comment]
@achingbrain @mxinden I can't assign you as reviewers but ptal

**Review by mxinden — APPROVED** [review]
Change looks good to me. Thanks @p-shahi.

Suggest waiting for @achingbrain as I am not a maintainer of any of these protocols.

Would it make sense to change the `status` column from `draft` to `deprecated`?

**Comment by mxinden** [comment]
Not a strong opinion on the `status` field change. See also https://github.com/multiformats/multicodec#status.

**Review by achingbrain — APPROVED** [review]

**Comment by BigLep** [comment]
@p-shahi @mxinden : we have two approvals.  Can one of you handle merging?  (This came up during IPLD triage.)

**Comment by p-shahi** [comment]
> Would it make sense to change the status column from draft to deprecated?

Done.

**Pull request merged**
