### PR TITLE
feat: add BLS12-381 public keys

### PR DESCRIPTION
**Pull request by tplooker**
Adds the two variations of BLS12-381 public keys.

### CODE REVIEW

**Comment by rvagg** [comment]
Actually, if we're accepting the `_` in #171 to make BLS12-381 clearer then I'd suggest the names be `bls12_381-g1-pub` and `bls12_381-g2-pub`. @vmx?

**Comment by OR13** [comment]
+1 have plans to use this asap :)

**Comment by tplooker** [comment]
@rvagg are we able to merge this?

**Comment by rvagg** [comment]
Yeah, but I don't have access to do it. Will chase someone down or get access myself to do it.

**Comment by rvagg** [comment]
👌

**Pull request merged**
