### PR TITLE
Add Ceramic Document Id

### PR DESCRIPTION
**Pull request by oed**
Adds an entry for Ceramic Document Ids, as `0xce`. I think this would be a `namespace`, but let me know if it should be something different!

See how it's used: https://github.com/ceramicnetwork/CIP/issues/59

### CODE REVIEW

**Comment by oed** [comment]
Ping, any blockers here?

**Review by vmx — APPROVED** [review]
Thanks for pinging, it slipped my attention.

Sounds good to me, I'd like to have one more approval from @rvagg or @Stebalien before merging.

**Comment by rvagg** [comment]
@oed would it be a problem for this to be in the two-byte range rather than taking up another slot in the quickly-filling-up single byte range? We're trying to push newer entries down in the table unless there's good reason for something to be that short, because of the space premium at the top.

**Comment by oed** [comment]
@rvagg Every update made to a ceramic document needs to contain the document id currently. Trimming one byte of the DocID would definitely be preferable!

**Comment by vmx** [comment]
It is already in the two-byte range as it is > `0x80`. The bytes in the list are the raw identifiers, and not the varints.

**Comment by oed** [comment]
Right, my bad. I guess I'd be fine with this.

**Review by rvagg — APPROVED** [review]

**Comment by vmx** [comment]
@oed Please rebase once more and I'll merge it right after.

**Comment by oed** [comment]
@vmx done!

**Pull request merged**
