### PR TITLE
Adds Textile Thread multiaddr

### PR DESCRIPTION
**Pull request by carsonfarmer**
The thread protocol is now relatively well-recognized in the community. Perhaps its time to make it official?

### CODE REVIEW

**Review by sbiaudet — APPROVED** [review]

**Review by sbiaudet — APPROVED** [review]

**Comment by Stebalien** [comment]
What is a thread multiaddr used to address? Usually, multiaddrs are used to address endpoints/machines, not resources/content.

However, this issue comes up so frequently I'm writing a proposal to see if we can unify around a "multipath" concept: https://github.com/multiformats/multiformats/pull/55.

**Comment by carsonfarmer** [comment]
Yup, multiformats/multiformats#55 is probably _exactly_ what we're looking for. In theory, a thread multiaddr is used to address a resource available via a particular peer/endpoint. But it _does_ go one step further than "endpoint/machine" to address a resource.

**Comment by carsonfarmer** [comment]
I see the conversation around the above linked "multipath" proposal is somewhat stalled. What is the likelihood of moving forward on that, versus just working with the code proposed in this PR?

**Comment by rvagg** [comment]
@Stebalien you're probably the authority for that question ^, specifically does:

> But it does go one step further than "endpoint/machine" to address a resource.

raise `thread` to being something we can fit in here?

**Comment by Stebalien** [comment]
Yes, that's why I made the multipath proposal. It's a simple generalization of multiaddr.

**Review by rvagg — APPROVED** [review]

**Pull request merged**
