### PR TITLE
chore: switch from Travis to Github Actions for validate

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]

**Comment by rvagg** [comment]
Might need @Stebalien or someone else with higher perms to change the rules for this repo to allow it to be merged without Travis passing.

**Comment by marten-seemann** [comment]
Done. Deleted both the required check and the Travis webhook.

**Comment by rvagg** [comment]
@marten-seemann cool, maybe you could enable required for the new action then in place

**Comment by marten-seemann** [comment]
Done.

**Pull request merged**
